#!/bin/sh

set -e

# Bootstrap if required
test -x bin/rspec || script/bootstrap

# Get cookbook name from metadata.rb or PWD
COOKBOOK_NAME="$(sed -n "s/name.*\"\(.*\)\"/\1/p" metadata.rb)"
: ${COOKBOOK_NAME:=$(basename "$PWD")}

# Prepare cookbook folder and run RSpec tests
COOKBOOKS_PATH="cookbooks"
rm -rf "$COOKBOOKS_PATH"
mkdir -p "$COOKBOOKS_PATH"
ln -snf ../ "$COOKBOOKS_PATH/$COOKBOOK_NAME"
exec bin/rspec $RSPEC_OPTS "$COOKBOOKS_PATH/$COOKBOOK_NAME/spec"
